# Copyright (c) 2019-2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

FROM ubuntu:bionic

RUN apt-get update \
    && apt-get install -y rpm ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists

ADD release-bin/deplab-linux-amd64 /usr/local/bin/deplab
