# Copyright (c) 2019-2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

FROM ubuntu:bionic as builder

RUN mkdir -p /all-files/folder

WORKDIR /all-files

RUN mkdir -p broken-folder/no-permissions \
    && echo 'no-permissions' > broken-folder/no-permissions/foo \
    && chmod 000 broken-folder/no-permissions

FROM scratch

COPY --from=builder /all-files/ /all-files

LABEL foo="bar"
