# Copyright (c) 2019-2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

FROM ubuntu:bionic-20190718

RUN echo 'deb http://example.com/ubuntu getdeb example' > /etc/apt/sources.list.d/example.list